[CXF-8378]:Fix NoClassDefFoundError: org/apache/cxf/common/util/Refle… (#728)
* [CXF-8378]:Fix NoClassDefFoundError: org/apache/cxf/common/util/ReflectionUtil

(cherry picked from commit 2acb47125c3ab36278648128f93e5ec456bcd713)