Merged revisions 1233355 via svnmerge from https://svn.apache.org/repos/asf/cxf/trunk
........
  r1233355 | sergeyb | 2012-01-19 13:23:11 +0000 (Thu, 19 Jan 2012) | 1 line
  
  [CXF-4045] Updating BusFactory to catch NoClassDefFoundError with minor refactoring to pass the Checkstyle
........


git-svn-id: https://svn.apache.org/repos/asf/cxf/branches/2.5.x-fixes@1233359 13f79535-47bb-0310-9956-ffa450edef68